import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// ES Module fix for __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Types matching the plan
interface VideoEntry {
    videoUrl: string;
    source: string; // "Matignon-LSF"
    score: number; // 0.0 to 1.0 confidence
}

type VideoIndex = Record<string, VideoEntry[]>;

const OUTPUT_DIR = path.join(__dirname, '../public/matignon');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'index.json');

// Mock Data - In a real scenario, this would be generated by parsing subtitles and mapping to clips
const MOCK_INDEX: VideoIndex = {
    "BONJOUR": [
        { videoUrl: "/matignon/clips/bonjour_01.mp4", source: "Matignon-LSF", score: 0.95 }
    ],
    "MERCI": [
        { videoUrl: "/matignon/clips/merci_01.mp4", source: "Matignon-LSF", score: 0.98 }
    ],
    "MAISON": [
        { videoUrl: "/matignon/clips/maison_01.mp4", source: "Matignon-LSF", score: 0.90 }
    ],
    "TRAVAIL": [
        { videoUrl: "/matignon/clips/travail_01.mp4", source: "Matignon-LSF", score: 0.85 }
    ],
    "AMOUR": [
        { videoUrl: "/matignon/clips/amour_01.mp4", source: "Matignon-LSF", score: 0.92 }
    ],
    "SAMEDI": [
        { videoUrl: "/matignon/clips/samedi_01.mp4", source: "Matignon-LSF", score: 0.88 }
    ],
    "SOIR": [
        { videoUrl: "/matignon/clips/soir_01.mp4", source: "Matignon-LSF", score: 0.88 }
    ],
    "FÊTE": [
        { videoUrl: "/matignon/clips/fete_01.mp4", source: "Matignon-LSF", score: 0.88 }
    ],
    "OÙ": [
        { videoUrl: "/matignon/clips/ou_01.mp4", source: "Matignon-LSF", score: 0.88 }
    ]
};

async function buildIndex() {
    console.log("Building Matignon-LSF Mock Index...");

    if (!fs.existsSync(OUTPUT_DIR)) {
        console.log(`Creating directory: ${OUTPUT_DIR}`);
        fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    // Double check strict JSON format
    const jsonContent = JSON.stringify(MOCK_INDEX, null, 2);

    fs.writeFileSync(OUTPUT_FILE, jsonContent);
    console.log(`Index successfully written to: ${OUTPUT_FILE}`);
    console.log(`Total entries: ${Object.keys(MOCK_INDEX).length}`);
}

buildIndex().catch(err => {
    console.error("Failed to build index:", err);
    process.exit(1);
});
